export const products = [
  {
    slug: "fitness-athletes-upgrade-portable-ice-bath",
    name: "Fitness Athletes Upgrade Portable Ice Bath Tub",
    shortName: "Fitness Athletes Pro",
    price: "$69.99",
    rating: 4.4,
    reviews: 128,
    image: "https://m.media-amazon.com/images/I/613b502x1hL._AC_SX679_.jpg",
    amazonLink: "https://www.amazon.com/Fitness-Athletes-Upgrade-Portable-recovery/dp/B0DXVHQKXB",
    features: [
      "Quick 3-step setup in under 5 minutes",
      "6-layer thermal insulation + aluminum foil layer",
      "Reinforced stainless steel support brackets",
      "Oval design with premium black exterior",
      "Built-in drainage valve + protective cover included",
    ],
    description:
      "The upgraded 2025 Fitness Athletes ice bath features enhanced insulation and structural support for daily cold therapy. Perfect for athletes, fitness enthusiasts, and home recovery routines. Folds compactly for storage and includes all accessories needed for immediate use.",
    specifications: {
      capacity: "130 gallons",
      dimensions: '47"L x 25.6"W x 27.5"H',
      weight: "10.2 lbs",
      material: "6-Ply PVC + Aluminum Alloy + Thermal Insulation",
    },
    pros: [
      "Extremely easy and fast setup",
      "Excellent insulation – stays cold 8+ hours",
      "Very sturdy once filled",
      "Great value for premium features",
      "Includes repair kit and phone holder",
    ],
    cons: ["Slightly confusing initial instructions", "Needs two people for first-time setup"],
  },
  {
    slug: "ice-bath-tub-athletes-xl",
    name: "Ice Bath Tub for Athletes with Cover - XL Portable Cold Plunge Tub",
    shortName: "XL Ice Bath Tub",
    price: "$89.99",
    rating: 4.6,
    reviews: 892,
    image: "https://m.media-amazon.com/images/I/61E4jg4sWFL._AC_SX679_.jpg",
    amazonLink: "https://www.amazon.com/Ice-Bath-Tub-Athletes-XL/dp/B0C3M9PD5X",
    features: [
      "Extra-large 42-inch height for full immersion (up to 6'6\")",
      "5-layer insulated walls with TPU & nylon",
      "All-weather cover with zipper lock",
      "Dual drainage system (top + bottom)",
      "Fits 120kg+ users comfortably",
    ],
    description:
      "The #1 bestselling portable ice bath on Amazon in 2025. Designed specifically for tall athletes and deep immersion therapy. Used by UFC fighters, NBA players, and CrossFit champions. Sets up in 3 minutes, holds ice for over 10 hours.",
    specifications: {
      capacity: "158 gallons",
      dimensions: '33"L x 33"W x 42"H',
      weight: "11.9 lbs",
      material: "Military-grade TPU + Pearl Cotton Insulation",
    },
    pros: [
      "Truly XL – perfect for tall people",
      "Best insulation in class",
      "Extremely popular with athletes",
      "Heavy-duty materials that last",
      "Easy to drain and clean",
    ],
    cons: ["Higher price than basic models", "Takes more ice to fill"],
  },
  {
    slug: "ice-pod-pro-extra-insulated",
    name: "Ice Pod Pro - Extra Insulated Cold Plunge Tub",
    shortName: "Ice Pod Pro",
    price: "$124.95",
    rating: 4.7,
    reviews: 213,
    image: "https://m.media-amazon.com/images/I/51CSBcDJDAL._AC_SX679_.jpg",
    amazonLink: "https://www.amazon.com/Ice-Pod-Pro-Extra-Insulated-Performance/dp/B0F74Q25ZR",
    features: [
      "Thickest walls on the market (50mm insulation)",
      "Reinforced thermal lid with weatherproof zipper",
      "UV-resistant 1000D nylon exterior",
      "Compatible with 1HP water chillers",
      "Professional-grade drainage hose",
    ],
    description:
      "The Ice Pod Pro is built for serious cold therapy enthusiasts who demand maximum insulation and durability. Used by professional sports teams and biohackers worldwide. Maintains 34°F for 12+ hours even in summer.",
    specifications: {
      capacity: "110 gallons",
      dimensions: '31.5"L x 31.5"W x 30"H',
      weight: "12.8 lbs",
      material: "1000D Nylon + 50mm Pearl Foam + PVC Liner",
    },
    pros: [
      "Best insulation available",
      "Built like a tank – lasts years",
      "Professional team favorite",
      "Perfect size for home gyms",
      "Chiller-ready design",
    ],
    cons: ["Premium price", "Slightly heavier than basic pods"],
  },
  {
    slug: "arctic-wolf-recovery-inflatable-ice-bath",
    name: "Arctic Wolf Recovery - Inflatable Ice Bath for Athletes",
    shortName: "Arctic Wolf",
    price: "$54.99",
    rating: 4.8,
    reviews: 56,
    image: "https://m.media-amazon.com/images/I/71aOoh+3hwL._AC_SX679_.jpg",
    amazonLink: "https://www.amazon.com/Arctic-Wolf-Recovery-Athletes-Inflatable/dp/B0D365TLFM",
    features: [
      "Dual-chamber anti-leak technology",
      "6-layer insulation with aluminum reflective film",
      "Double inflatable ring for maximum stability",
      "Rapid inflation valve (under 2 minutes)",
      "Includes electric air pump ($29 value)",
    ],
    description:
      "The Arctic Wolf features revolutionary dual-chamber construction that prevents leaks even if punctured. Perfect for beginners and budget-conscious users who want pro-level features without the high cost.",
    specifications: {
      capacity: "98 gallons",
      dimensions: '30"L x 30"W x 33.5"H',
      weight: "9.3 lbs",
      material: "Reinforced PVC + Aluminum Foil Insulation",
    },
    pros: [
      "Best value under $60",
      "Includes electric pump!",
      "Innovative leak-proof design",
      "Surprisingly good insulation",
      "Great customer service",
    ],
    cons: ["Pump quality is average", "Takes practice to fold perfectly"],
  },
  {
    slug: "shark-facialpro-hydro-powered",
    name: "Shark FacialPro - At-Home Hydro-Powered Ice Facial Device",
    shortName: "Shark FacialPro",
    price: "$39.99",
    rating: 4.5,
    reviews: 342,
    image: "https://m.media-amazon.com/images/I/71l7Zq2vjQL._SX679_.jpg",
    amazonLink: "https://www.amazon.com/Shark-FacialPro-at-Home-Hydro-Powered-DePuffi/dp/B0FMTN1V3G",
    features: [
      "Hydro-powered ice facial system (no batteries)",
      "360° rotating ice mold for full-face coverage",
      "De-puffs in 60 seconds",
      "Dermatologist-recommended for rosacea & acne",
      "Includes 2 silicone molds + storage case",
    ],
    description:
      "The viral Shark FacialPro brings spa-grade ice facials to your home. Clinically proven to reduce puffiness, shrink pores, and boost circulation. Used by celebrities and estheticians worldwide.",
    specifications: {
      capacity: "N/A (facial tool)",
      dimensions: '6.5" x 4.2" x 2.1"',
      weight: "0.9 lbs",
      material: "Medical-grade Silicone + Stainless Steel",
    },
    pros: [
      "Actually works – visible results in days",
      "No electricity or ice bags needed",
      "Perfect for morning routine",
      "Great for migraines too",
      "Excellent gift choice",
    ],
    cons: ["Learning curve for first use", "Mold needs freezer space"],
  },
  {
    slug: "wxtkkom-upgraded-multi-layered-bathtub",
    name: "Wxtkkom Upgraded Multi-Layered Inflatable Ice Bath",
    shortName: "Wxtkkom Pro Tub",
    price: "$65.99",
    rating: 4.3,
    reviews: 89,
    image: "https://m.media-amazon.com/images/I/71JMNCsRO5L._AC_SX679_.jpg",
    amazonLink: "https://www.amazon.com/Wxtkkom-Upgraded-Multi-Layered-Inflatable-Bathtubs/dp/B0FMD7GPRV",
    features: [
      "8-layer professional insulation system",
      "Anti-collapse reinforced frame",
      "Temperature retention up to 14 hours",
      "Built-in thermometer strip",
      "Supports 400+ lbs",
    ],
    description:
      "The Wxtkkom 2025 Pro Series features aerospace-grade insulation materials previously only available in $1000+ tubs. Independently tested to maintain 35°F water for 14 hours in 90°F ambient temperature.",
    specifications: {
      capacity: "105 gallons",
      dimensions: '32"L x 32"W x 30"H',
      weight: "10.8 lbs",
      material: "8-Layer Composite (PVC + Nylon + Foam + Foil)",
    },
    pros: [
      "Insane temperature retention",
      "Feels premium despite price",
      "Very stable – no tipping",
      "Includes digital thermometer",
      "Excellent drainage design",
    ],
    cons: ["Setup takes 8-10 minutes", "Air valve can be tricky"],
  },
  {
    slug: "aqua-lung-leg3nd-elite-regulator",
    name: "Aqua Lung Leg3nd Elite Scuba Diving Regulator",
    shortName: "LEG3ND ELITE",
    price: "$799.00",
    rating: 4.9,
    reviews: 412,
    image: "https://m.media-amazon.com/images/I/61uzQ1FvRSL._AC_SX679_.jpg",
    amazonLink: "https://www.amazon.com/Aqua-Lung-Leg3nd-Elite-Regulator/dp/B0848JGNNB",
    features: [
      "Master Breathing System (MBS) dual control",
      "Auto Closure Device (ACD) – keeps water out",
      "Deep ribbed diaphragm for ice diving",
      "Ergonomic venturi switch",
      "Heat exchanger for cold water performance",
    ],
    description:
      "The ultimate regulator for technical and ice divers. The LEG3ND ELITE combines legendary Aqua Lung performance with cutting-edge cold-water technology. Trusted by rescue divers in Antarctica and Great Lakes ice divers.",
    specifications: {
      capacity: "N/A (scuba regulator)",
      dimensions: 'First stage: 2.8" diameter',
      weight: "2.3 lbs (full set)",
      material: "Marine-grade brass + PVD coating",
    },
    pros: [
      "Best breathing performance in cold water",
      "Zero free-flow issues in ice diving",
      "Lifetime warranty on first stage",
      "Incredibly smooth inhale/exhale",
      "Beautiful design",
    ],
    cons: ["Premium price", "Overkill for warm water diving"],
  },
]
